import { Request, Response, NextFunction } from 'express';
import { v4 as uuidv4 } from 'uuid';
import { als } from '../utils/asyncStorage'; // Shared ALS instance

export const correlationIdMiddleware = (req: Request, res: Response, next: NextFunction) => {
  const store = new Map<string, any>();
  // Get the request ID generated by pino-http (available on req.id)
  // pino-http also sets the 'X-Request-Id' header, so we don't need to do it here explicitly.
  let correlationId = (req as any).id || req.headers['x-correlation-id'];

  if (!correlationId) {
    // Fallback if pino-http somehow didn't set an ID - generate our own
    correlationId = uuidv4();
    console.warn(
      '[correlationIdMiddleware] pino-http did not provide req.id. Generated fallback correlationId.'
    );
  }

  store.set('correlationId', correlationId);
  // For convenience, ensure req.correlationId is also set
  (req as any).correlationId = correlationId;
  res.setHeader('x-correlation-id', correlationId);

  als.run(store, () => {
    next();
  });
};
