export enum IngestionErrorCode {
  PDF_PARSE_FAILED = 'PDF_PARSE_FAILED',
  EXCEL_PARSE_FAILED = 'EXCEL_PARSE_FAILED',
  IMAGE_PROCESS_FAILED = 'IMAGE_PROCESS_FAILED',
  AUDIO_PROCESS_FAILED = 'AUDIO_PROCESS_FAILED',
  VIDEO_PROCESS_FAILED = 'VIDEO_PROCESS_FAILED',
  UNSUPPORTED_FILE_TYPE = 'UNSUPPORTED_FILE_TYPE',
  S3_OPERATION_FAILED = 'S3_OPERATION_FAILED',
  OPENAI_EMBEDDING_FAILED = 'OPENAI_EMBEDDING_FAILED',
  PINECONE_UPSERT_FAILED = 'PINECONE_UPSERT_FAILED',
  PINECONE_DELETE_FAILED = 'PINECONE_DELETE_FAILED',
  LARGE_FILE_MEMORY_EXCEEDED = 'LARGE_FILE_MEMORY_EXCEEDED',
  DOCUMENT_NOT_FOUND = 'DOCUMENT_NOT_FOUND',
  MISSING_MIMETYPE = 'MISSING_MIMETYPE',
  NO_TEXT_EXTRACTED = 'NO_TEXT_EXTRACTED',
  CHUNK_EMBEDDING_MISMATCH = 'CHUNK_EMBEDDING_MISMATCH',
  DATABASE_UPDATE_FAILED = 'DATABASE_UPDATE_FAILED',
  CONTENT_HASH_MISMATCH = 'CONTENT_HASH_MISMATCH', // For potential future use if a retry finds different content for same ID
  DUPLICATE_CONTENT_COMPLETED = 'DUPLICATE_CONTENT_COMPLETED', // Idempotency: existing completed doc found
  DUPLICATE_CONTENT_PROCESSING = 'DUPLICATE_CONTENT_PROCESSING', // Idempotency: existing doc in progress
  NAMESPACE_ERROR = 'NAMESPACE_ERROR', // New error code for namespace resolution issues
  UNKNOWN_PROCESSING_ERROR = 'UNKNOWN_PROCESSING_ERROR',
}
