import Link from "next/link";

export default function HomePage() {
  return (
    <div className="min-h-screen flex flex-col items-center justify-center bg-gradient-to-b from-blue-500 to-purple-600 text-white">
      <h1 className="text-6xl font-bold mb-4">Platform Runner</h1>
      <p className="text-xl mb-8">A Mario-style platformer with AI-generated sprites</p>
      <Link
        href="/game"
        className="bg-white text-purple-600 px-8 py-4 rounded-lg font-bold text-xl hover:bg-gray-100 transition"
      >
        Start Game
      </Link>
      <div className="mt-8 text-sm opacity-75">
        <p>Built with Next.js 15 + Phaser 3</p>
        <p>Sprites generated by PixelLab AI</p>
      </div>
    </div>
  );
}
